CATEGORY_MAP = {
    "automotive_accessories": "Phụ kiện Ô tô",
    "baby_products": "Sản phẩm Trẻ em",
    "beauty_makeup": "Trang điểm",
    "beauty_skincare": "Chăm sóc Da",
    "electronics_gaming_consoles": "Máy chơi Game",
    "electronics_headphones": "Tai nghe",
    "electronics_keyboards": "Bàn phím",
    "electronics_laptops": "Laptop",
    "electronics_monitors": "Màn hình",
    "electronics_networking": "Thiết bị Mạng",
    "electronics_smartphones": "Điện thoại",
    "electronics_storage_ssd": "Ổ cứng SSD",
    "electronics_tablets": "Máy tính bảng",
    "fashion_bags": "Túi xách",
    "fashion_mens": "Thời trang Nam",
    "fashion_shoes": "Giày dép",
    "fashion_womens": "Thời trang Nữ",
    "health_personal_care": "Chăm sóc Cá nhân",
    "health_supplements": "Thực phẩm CN",
    "home_air_quality": "Máy lọc Không khí",
    "home_cleaning": "Vệ sinh Nhà cửa",
    "home_furniture": "Nội thất",
    "home_kitchen_appliances": "Đồ gia dụng",
    "office_stationery": "Văn phòng phẩm",
    "office_supplies": "Thiết bị VP",
    "pet_supplies": "Thú cưng",
    "sports_fitness": "Thể hình",
    "sports_outdoors": "Thể thao",
    "tools_home_improvement": "Dụng cụ Sửa chữa",
    "toys_games": "Đồ chơi",
}
